const CATALOG_DATA = [
  {
    id: 1,
    name: "Farmer Box",
    price: 35,
    imageUrl: "https://i.ibb.co/sbM3b0W/Screenshot-2020-11-22-at-12-23-33.png",
    includes: [
      "6 Organic Eggs",
      "6 Plain Sausages",
      "6 Bacon Rashers",
      "2 Pork Chops",
      "2 Lamb Rump Steaks",
      "2 Chicken Fillets",
      "500g Beef Mince",
    ],
  },
  {
    id: 2,
    name: "Family Box",
    price: 60,
    imageUrl: "https://i.ibb.co/8KxGvQL/Screenshot-2020-11-22-at-15-14-18.png",
    includes: [
      "12 Organic Eggs",
      "12 Plain Sausages",
      "12 Bacon Rashers",
      "4 Pork Chops",
      "4 Lamb Rump Steaks",
      "4 Chicken Fillets",
      "1kg Beef Mince",
    ],
  },
  {
    id: 3,
    name: "Feast Box",
    price: 100,
    imageUrl: "https://i.ibb.co/SV3rw0p/Screenshot-2020-11-22-at-15-15-32.png",
    includes: [
      "12 Organic Eggs",
      "12 Plain Sausages",
      "12 Bacon Rashers",
      "4 Pork Chops",
      "4 Lamb Rump Steaks",
      "4 Chicken Fillets",
      "1kg Beef Mince",
      "2 Fillet Steaks (100g each)",
      "2 Rump Steaks (300g each)",
      "2 Sirloin Steaks (200g each)",
      "2 Ribeye Steaks (200g each)",
    ],
  },
  {
    id: 4,
    name: "Breakfast Box",
    price: 25,
    imageUrl: "https://i.ibb.co/x1n9Z9q/Screenshot-2020-11-22-at-15-16-19.png",
    includes: [
      "12 Organic Eggs",
      "8 Plain Sausages",
      "8 Bacon Rashers",
      "8 Black Puddings",
    ],
  },
  {
    id: 5,
    name: "Steak Box",
    price: 45,
    imageUrl: "https://i.ibb.co/BV1YYJj/Screenshot-2020-11-22-at-15-17-04.png",
    includes: [
      "2 Fillet Steaks (100g each)",
      "2 Rump Steaks (300g each)",
      "2 Sirloin Steaks (200g each)",
      "2 Ribeye Steaks (200g each)",
    ],
  },
  {
    id: 6,
    name: "Slow Cooker Box",
    price: 25,
    imageUrl: "https://i.ibb.co/tsF33W7/Screenshot-2020-11-22-at-15-17-43.png",
    includes: [
      "Diced Beef (500g)",
      "Diced Lamb (500g)",
      "Diced Pork (500g)",
      "Diced Chicken (500g)",
    ],
  },
  {
    id: 7,
    name: "Roast Box",
    price: 45,
    imageUrl: "https://i.ibb.co/tBvzTJ6/Screenshot-2020-11-22-at-15-18-36.png",
    includes: [
      "Rolled Pork Loin (1.5kg)",
      "Corner Cut Beef Topside Joint (1.5kg)",
    ],
  },
  {
    id: 8,
    name: "Sunday Box",
    price: 45,
    imageUrl: "https://i.ibb.co/KjGpZTW/Screenshot-2020-11-22-at-15-19-15.png",
    includes: ["Half Leg of Lamb (1.5kg)", "Whole Chicken (2kg)"],
  },
  {
    id: 9,
    name: "Smoker Box",
    price: 35,
    imageUrl: "https://i.ibb.co/Vmz1bTj/Screenshot-2020-11-22-at-15-19-49.png",
    includes: [
      "Boned & Rolled Beef Brisket (1.5kg)",
      "Boned & Rolled Pork Shoulder (1.5kg)",
    ],
  },
  {
    id: 10,
    name: "Lamb Box",
    price: 100,
    imageUrl: "https://i.ibb.co/qY7PXYS/Screenshot-2020-11-22-at-15-20-23.png",
    includes: [
      "1 Neck Fillet",
      "5 Loin Chops",
      "6 Cutlets",
      "2 Chump Chops",
      "1 Shoulder",
      "1 Leg",
      "1 Boneless Breast",
      "500g  Mince",
    ],
  },
  {
    id: 11,
    name: "Beef Box",
    price: 40,
    imageUrl: "https://i.ibb.co/V3mJrcY/Screenshot-2020-11-22-at-15-21-07.png",
    includes: [
      "4 Beef Burgers",
      "500g Diced Beef",
      "500g Minced Beef",
      "500g Bavette Strips",
      "1kg Topside Joint",
    ],
  },
  {
    id: 12,
    name: "Pork Box",
    price: 40,
    imageUrl: "https://i.ibb.co/3pPfkpp/Screenshot-2020-11-22-at-15-21-55.png",
    includes: [
      "4 Boneless Pork Chops",
      "4 Pork Belly Strips",
      "500g Diced Pork",
      "500g Minced Pork",
      "1kg Boneless Loin Joint",
    ],
  },
  {
    id: 13,
    name: "Chicken Box",
    price: 40,
    imageUrl: "https://i.ibb.co/hgbzTVP/Screenshot-2020-11-22-at-15-22-31.png",
    includes: [
      "4 Chicken Breast",
      "4 Chicken Thighs",
      "500g Diced Chicken",
      "500g Chicken Strips",
      "1 Whole Chicken",
    ],
  },
];

export default CATALOG_DATA;
